"""Bilingual starter catalog for a full-service Indian cafe.

Names intentionally follow ``English (Hindi)`` so staff can search and read
the same record.  Category and workstation values use the Inventory OS
vocabulary and can be edited later without changing stock history.
"""

from __future__ import annotations


INVENTORY_CATEGORIES = {
    "Fresh Produce": ("leaf", "#6cab7a"),
    "Fruits": ("apple", "#db8b64"),
    "Dairy": ("milk", "#6ea8fe"),
    "Coffee & Beverages": ("cup-soda", "#8b5e3c"),
    "Bakery & Confectionery": ("cake-slice", "#d49a89"),
    "Groceries": ("package", "#b08968"),
    "Masalas & Seasonings": ("wheat", "#c98245"),
    "Sauces & Condiments": ("bottle-wine", "#b45f50"),
    "Packaging & Disposables": ("box", "#d0a85c"),
    "Cleaning Products": ("sparkles", "#9aa6b2"),
    "Toiletries & Washroom": ("droplets", "#89a6b8"),
    "Kitchen Supplies": ("utensils", "#a17755"),
    "Maintenance & Equipment": ("cog", "#7c7f8a"),
    "Gas & Fuel": ("flame", "#de7c4a"),
    "Water & Ice": ("droplets", "#6aa9c8"),
    "Utility": ("bolt", "#d6a75b"),
}


def item(
    english: str,
    hindi: str,
    category: str,
    subcategory: str,
    item_type: str,
    area: str,
    unit: str,
    storage: str,
) -> dict:
    return {
        "english": english,
        "hindi": hindi,
        "name": f"{english} ({hindi})",
        "category": category,
        "subcategory": subcategory,
        "item_type": item_type,
        "area": area,
        "unit": unit,
        "storage": storage,
    }


CATALOG_ITEMS = [
    # Fresh vegetables, herbs, and kitchen produce
    item("Potato", "आलू", "Fresh Produce", "Root Vegetables", "perishable", "north", "kg", "Cool dry store"),
    item("Cucumber", "खीरा", "Fresh Produce", "Salad Vegetables", "perishable", "continental", "kg", "Refrigerator"),
    item("Tomato", "टमाटर", "Fresh Produce", "Everyday Vegetables", "perishable", "kitchen", "kg", "Refrigerator"),
    item("Fresh Green Chilli", "हरी मिर्च", "Fresh Produce", "Fresh Herbs & Aromatics", "perishable", "kitchen", "kg", "Refrigerator"),
    item("Fresh Coriander Leaves", "हरा धनिया", "Fresh Produce", "Fresh Herbs & Aromatics", "perishable", "kitchen", "kg", "Refrigerator"),
    item("Onion", "प्याज", "Fresh Produce", "Everyday Vegetables", "perishable", "kitchen", "kg", "Cool dry store"),
    item("Cabbage", "पत्तागोभी", "Fresh Produce", "Leafy Vegetables", "perishable", "chinese", "kg", "Refrigerator"),
    item("Mint Leaves", "पुदीना", "Fresh Produce", "Fresh Herbs & Aromatics", "perishable", "barista", "kg", "Refrigerator"),
    item("Green Capsicum", "हरी शिमला मिर्च", "Fresh Produce", "Capsicum", "perishable", "continental", "kg", "Refrigerator"),
    item("Red Capsicum", "लाल शिमला मिर्च", "Fresh Produce", "Capsicum", "perishable", "continental", "kg", "Refrigerator"),
    item("Yellow Capsicum", "पीली शिमला मिर्च", "Fresh Produce", "Capsicum", "perishable", "continental", "kg", "Refrigerator"),
    item("Spinach", "पालक", "Fresh Produce", "Leafy Vegetables", "perishable", "north", "kg", "Refrigerator"),
    item("Garlic", "लहसुन", "Fresh Produce", "Fresh Herbs & Aromatics", "perishable", "kitchen", "kg", "Cool dry store"),
    item("Carrot", "गाजर", "Fresh Produce", "Root Vegetables", "perishable", "kitchen", "kg", "Refrigerator"),
    item("Pumpkin", "कद्दू", "Fresh Produce", "Everyday Vegetables", "perishable", "north", "kg", "Cool dry store"),
    item("Bottle Gourd", "लौकी", "Fresh Produce", "Everyday Vegetables", "perishable", "north", "kg", "Refrigerator"),
    item("Lemon", "नींबू", "Fresh Produce", "Citrus", "perishable", "barista", "kg", "Refrigerator"),
    item("Cauliflower", "फूलगोभी", "Fresh Produce", "Everyday Vegetables", "perishable", "north", "kg", "Refrigerator"),
    item("Ginger", "अदरक", "Fresh Produce", "Fresh Herbs & Aromatics", "perishable", "kitchen", "kg", "Refrigerator"),
    item("Broccoli", "ब्रोकली", "Fresh Produce", "Continental Vegetables", "perishable", "continental", "kg", "Refrigerator"),
    item("French Beans", "फ्रेंच बीन्स", "Fresh Produce", "Everyday Vegetables", "perishable", "continental", "kg", "Refrigerator"),
    item("Lettuce", "सलाद पत्ता", "Fresh Produce", "Salad Vegetables", "perishable", "continental", "kg", "Refrigerator"),
    item("Beetroot", "चुकंदर", "Fresh Produce", "Root Vegetables", "perishable", "continental", "kg", "Refrigerator"),
    item("Mushroom", "मशरूम", "Fresh Produce", "Continental Vegetables", "perishable", "continental", "kg", "Refrigerator"),
    item("Spring Onion", "हरा प्याज", "Fresh Produce", "Fresh Herbs & Aromatics", "perishable", "chinese", "kg", "Refrigerator"),
    item("Green Peas", "हरी मटर", "Fresh Produce", "Everyday Vegetables", "perishable", "north", "kg", "Freezer"),
    item("Sweet Corn", "स्वीट कॉर्न", "Fresh Produce", "Continental Vegetables", "perishable", "continental", "kg", "Freezer"),
    item("Baby Corn", "बेबी कॉर्न", "Fresh Produce", "Indo-Chinese Vegetables", "perishable", "chinese", "kg", "Refrigerator"),
    item("Zucchini", "जुकिनी", "Fresh Produce", "Continental Vegetables", "perishable", "continental", "kg", "Refrigerator"),
    item("Celery", "सेलेरी", "Fresh Produce", "Fresh Herbs & Aromatics", "perishable", "continental", "kg", "Refrigerator"),
    item("Parsley", "पार्सले", "Fresh Produce", "Fresh Herbs & Aromatics", "perishable", "continental", "kg", "Refrigerator"),
    item("Fresh Basil", "ताजा तुलसी", "Fresh Produce", "Fresh Herbs & Aromatics", "perishable", "continental", "kg", "Refrigerator"),
    item("Curry Leaves", "करी पत्ता", "Fresh Produce", "Fresh Herbs & Aromatics", "perishable", "south", "kg", "Refrigerator"),
    item("Fresh Coconut", "ताजा नारियल", "Fresh Produce", "South Indian Produce", "perishable", "south", "pcs", "Cool dry store"),

    # Fruits for juices, shakes, desserts, and garnish
    item("Banana", "केला", "Fruits", "Milkshake Fruits", "perishable", "barista", "dozen", "Fruit rack"),
    item("Apple", "सेब", "Fruits", "Juice Fruits", "perishable", "barista", "kg", "Refrigerator"),
    item("Mango", "आम", "Fruits", "Seasonal Fruits", "perishable", "barista", "kg", "Refrigerator"),
    item("Orange", "संतरा", "Fruits", "Juice Fruits", "perishable", "barista", "kg", "Refrigerator"),
    item("Sweet Lime", "मौसंबी", "Fruits", "Juice Fruits", "perishable", "barista", "kg", "Refrigerator"),
    item("Pomegranate", "अनार", "Fruits", "Juice Fruits", "perishable", "barista", "kg", "Refrigerator"),
    item("Pineapple", "अनानास", "Fruits", "Juice Fruits", "perishable", "barista", "pcs", "Refrigerator"),
    item("Watermelon", "तरबूज", "Fruits", "Juice Fruits", "perishable", "barista", "kg", "Cool store"),
    item("Papaya", "पपीता", "Fruits", "Breakfast Fruits", "perishable", "north", "kg", "Refrigerator"),
    item("Strawberry", "स्ट्रॉबेरी", "Fruits", "Milkshake Fruits", "perishable", "barista", "kg", "Refrigerator"),
    item("Sapota", "चीकू", "Fruits", "Milkshake Fruits", "perishable", "barista", "kg", "Refrigerator"),
    item("Grapes", "अंगूर", "Fruits", "Juice Fruits", "perishable", "barista", "kg", "Refrigerator"),
    item("Kiwi", "कीवी", "Fruits", "Premium Fruits", "perishable", "barista", "pcs", "Refrigerator"),
    item("Avocado", "एवोकाडो", "Fruits", "Premium Fruits", "perishable", "continental", "pcs", "Refrigerator"),

    # Dairy, cheese, and chilled products
    item("Fresh Milk", "ताजा दूध", "Dairy", "Milk & Cream", "perishable", "barista", "litre", "Refrigerator"),
    item("UHT Milk Carton", "यूएचटी दूध", "Dairy", "Milk & Cream", "non_perishable", "barista", "litre", "Dry store"),
    item("Curd", "दही", "Dairy", "Curd & Yogurt", "perishable", "north", "kg", "Refrigerator"),
    item("Paneer", "पनीर", "Dairy", "Paneer & Cheese", "perishable", "north", "kg", "Refrigerator"),
    item("Desi Ghee", "देसी घी", "Dairy", "Butter & Ghee", "non_perishable", "kitchen", "kg", "Dry store"),
    item("White Butter", "सफेद मक्खन", "Dairy", "Butter & Ghee", "perishable", "north", "kg", "Refrigerator"),
    item("Salted Butter", "नमकीन मक्खन", "Dairy", "Butter & Ghee", "perishable", "continental", "kg", "Refrigerator"),
    item("Fresh Cream", "ताजा क्रीम", "Dairy", "Milk & Cream", "perishable", "continental", "litre", "Refrigerator"),
    item("Whipping Cream", "व्हिपिंग क्रीम", "Dairy", "Milk & Cream", "perishable", "barista", "litre", "Refrigerator"),
    item("Mozzarella Cheese", "मोज़रेला चीज़", "Dairy", "Paneer & Cheese", "perishable", "continental", "kg", "Refrigerator"),
    item("Processed Cheese", "प्रोसेस्ड चीज़", "Dairy", "Paneer & Cheese", "perishable", "continental", "kg", "Refrigerator"),
    item("Cheddar Cheese", "चेडर चीज़", "Dairy", "Paneer & Cheese", "perishable", "continental", "kg", "Refrigerator"),
    item("Cheese Slices", "चीज़ स्लाइस", "Dairy", "Paneer & Cheese", "perishable", "continental", "packet", "Refrigerator"),
    item("Condensed Milk", "गाढ़ा दूध", "Dairy", "Milk & Cream", "non_perishable", "barista", "tin", "Dry store"),
    item("Vanilla Ice Cream", "वनीला आइसक्रीम", "Dairy", "Ice Cream", "perishable", "barista", "litre", "Freezer"),
    item("Chocolate Ice Cream", "चॉकलेट आइसक्रीम", "Dairy", "Ice Cream", "perishable", "barista", "litre", "Freezer"),
    item("Butterscotch Ice Cream", "बटरस्कॉच आइसक्रीम", "Dairy", "Ice Cream", "perishable", "barista", "litre", "Freezer"),

    # Coffee, tea, juices, shakes, and cold beverages
    item("Coffee Beans", "कॉफी बीन्स", "Coffee & Beverages", "Coffee", "non_perishable", "barista", "kg", "Airtight dry store"),
    item("Espresso Blend Coffee Beans", "एस्प्रेसो कॉफी बीन्स", "Coffee & Beverages", "Coffee", "non_perishable", "barista", "kg", "Airtight dry store"),
    item("Instant Coffee", "इंस्टेंट कॉफी", "Coffee & Beverages", "Coffee", "non_perishable", "barista", "kg", "Dry store"),
    item("Filter Coffee Powder", "फिल्टर कॉफी पाउडर", "Coffee & Beverages", "Coffee", "non_perishable", "south", "kg", "Airtight dry store"),
    item("Tea Leaves", "चाय पत्ती", "Coffee & Beverages", "Tea", "non_perishable", "barista", "kg", "Dry store"),
    item("Green Tea Bags", "ग्रीन टी बैग", "Coffee & Beverages", "Tea", "non_perishable", "barista", "box", "Dry store"),
    item("Blue Pea Tea", "अपराजिता चाय", "Coffee & Beverages", "Tea", "non_perishable", "barista", "packet", "Dry store"),
    item("Cocoa Powder", "कोको पाउडर", "Coffee & Beverages", "Chocolate Drinks", "non_perishable", "barista", "kg", "Dry store"),
    item("Drinking Chocolate", "ड्रिंकिंग चॉकलेट", "Coffee & Beverages", "Chocolate Drinks", "non_perishable", "barista", "kg", "Dry store"),
    item("Vanilla Syrup", "वनीला सिरप", "Coffee & Beverages", "Flavour Syrups", "non_perishable", "barista", "bottle", "Barista shelf"),
    item("Caramel Syrup", "कैरेमल सिरप", "Coffee & Beverages", "Flavour Syrups", "non_perishable", "barista", "bottle", "Barista shelf"),
    item("Hazelnut Syrup", "हेज़लनट सिरप", "Coffee & Beverages", "Flavour Syrups", "non_perishable", "barista", "bottle", "Barista shelf"),
    item("Chocolate Syrup", "चॉकलेट सिरप", "Coffee & Beverages", "Flavour Syrups", "non_perishable", "barista", "bottle", "Barista shelf"),
    item("Strawberry Syrup", "स्ट्रॉबेरी सिरप", "Coffee & Beverages", "Flavour Syrups", "non_perishable", "barista", "bottle", "Barista shelf"),
    item("Mango Pulp", "आम का गूदा", "Coffee & Beverages", "Juice & Shake Bases", "non_perishable", "barista", "tin", "Dry store"),
    item("Mango Crush", "मैंगो क्रश", "Coffee & Beverages", "Juice & Shake Bases", "non_perishable", "barista", "bottle", "Barista shelf"),
    item("Strawberry Crush", "स्ट्रॉबेरी क्रश", "Coffee & Beverages", "Juice & Shake Bases", "non_perishable", "barista", "bottle", "Barista shelf"),
    item("Pineapple Crush", "पाइनएप्पल क्रश", "Coffee & Beverages", "Juice & Shake Bases", "non_perishable", "barista", "bottle", "Barista shelf"),
    item("Rose Syrup", "गुलाब सिरप", "Coffee & Beverages", "Traditional Drinks", "non_perishable", "barista", "bottle", "Barista shelf"),
    item("Khus Syrup", "खस सिरप", "Coffee & Beverages", "Traditional Drinks", "non_perishable", "barista", "bottle", "Barista shelf"),
    item("Soda Water", "सोडा पानी", "Coffee & Beverages", "Cold Beverages", "non_perishable", "barista", "bottle", "Beverage rack"),
    item("Mineral Water Bottle", "मिनरल वाटर बोतल", "Water & Ice", "Drinking Water", "non_perishable", "cafe", "bottle", "Beverage rack"),
    item("Ice Cubes", "बर्फ के टुकड़े", "Water & Ice", "Ice", "perishable", "barista", "kg", "Freezer"),

    # Bakery, breakfast, South Indian, and core groceries
    item("Pav Bread", "पाव ब्रेड", "Bakery & Confectionery", "Bread", "perishable", "north", "packet", "Bread rack"),
    item("Sandwich Bread", "सैंडविच ब्रेड", "Bakery & Confectionery", "Bread", "perishable", "continental", "loaf", "Bread rack"),
    item("Burger Buns", "बर्गर बन", "Bakery & Confectionery", "Bread", "perishable", "continental", "packet", "Bread rack"),
    item("Pizza Base", "पिज़्ज़ा बेस", "Bakery & Confectionery", "Pizza", "perishable", "continental", "pcs", "Refrigerator"),
    item("Bread Crumbs", "ब्रेड क्रम्ब्स", "Bakery & Confectionery", "Coating", "non_perishable", "continental", "kg", "Dry store"),
    item("All-Purpose Flour", "मैदा", "Groceries", "Flours", "non_perishable", "kitchen", "kg", "Dry store"),
    item("Whole Wheat Flour", "गेहूं का आटा", "Groceries", "Flours", "non_perishable", "north", "kg", "Dry store"),
    item("Gram Flour", "बेसन", "Groceries", "Flours", "non_perishable", "north", "kg", "Dry store"),
    item("Rice Flour", "चावल का आटा", "Groceries", "Flours", "non_perishable", "south", "kg", "Dry store"),
    item("Corn Flour", "कॉर्न फ्लोर", "Groceries", "Flours", "non_perishable", "chinese", "kg", "Dry store"),
    item("Semolina", "सूजी", "Groceries", "Breakfast Staples", "non_perishable", "north", "kg", "Dry store"),
    item("Flattened Rice", "पोहा", "Groceries", "Breakfast Staples", "non_perishable", "north", "kg", "Dry store"),
    item("Rolled Oats", "ओट्स", "Groceries", "Breakfast Staples", "non_perishable", "north", "kg", "Dry store"),
    item("Corn Flakes", "कॉर्न फ्लेक्स", "Groceries", "Breakfast Staples", "non_perishable", "north", "box", "Dry store"),
    item("Sago", "साबूदाना", "Groceries", "Breakfast Staples", "non_perishable", "north", "kg", "Dry store"),
    item("Idli Rice", "इडली चावल", "Groceries", "South Indian Staples", "non_perishable", "south", "kg", "Dry store"),
    item("Dosa Rice", "डोसा चावल", "Groceries", "South Indian Staples", "non_perishable", "south", "kg", "Dry store"),
    item("Basmati Rice", "बासमती चावल", "Groceries", "Rice", "non_perishable", "kitchen", "kg", "Dry store"),
    item("Regular Rice", "साधारण चावल", "Groceries", "Rice", "non_perishable", "kitchen", "kg", "Dry store"),
    item("Urad Dal", "उड़द दाल", "Groceries", "Pulses & Lentils", "non_perishable", "south", "kg", "Dry store"),
    item("Toor Dal", "अरहर दाल", "Groceries", "Pulses & Lentils", "non_perishable", "south", "kg", "Dry store"),
    item("Chana Dal", "चना दाल", "Groceries", "Pulses & Lentils", "non_perishable", "kitchen", "kg", "Dry store"),
    item("Moong Dal", "मूंग दाल", "Groceries", "Pulses & Lentils", "non_perishable", "north", "kg", "Dry store"),
    item("Black Chickpeas", "काला चना", "Groceries", "Pulses & Lentils", "non_perishable", "north", "kg", "Dry store"),
    item("White Chickpeas", "काबुली चना", "Groceries", "Pulses & Lentils", "non_perishable", "north", "kg", "Dry store"),
    item("Kidney Beans", "राजमा", "Groceries", "Pulses & Lentils", "non_perishable", "north", "kg", "Dry store"),
    item("Peanuts", "मूंगफली", "Groceries", "Nuts & Seeds", "non_perishable", "kitchen", "kg", "Dry store"),
    item("Cashew Nuts", "काजू", "Groceries", "Nuts & Seeds", "non_perishable", "barista", "kg", "Dry store"),
    item("Almonds", "बादाम", "Groceries", "Nuts & Seeds", "non_perishable", "barista", "kg", "Dry store"),
    item("Raisins", "किशमिश", "Groceries", "Nuts & Seeds", "non_perishable", "barista", "kg", "Dry store"),
    item("Sugar", "चीनी", "Groceries", "Sweeteners", "non_perishable", "barista", "kg", "Dry store"),
    item("Brown Sugar", "ब्राउन शुगर", "Groceries", "Sweeteners", "non_perishable", "barista", "kg", "Dry store"),
    item("Jaggery", "गुड़", "Groceries", "Sweeteners", "non_perishable", "north", "kg", "Dry store"),
    item("Tamarind", "इमली", "Groceries", "South Indian Staples", "non_perishable", "south", "kg", "Dry store"),
    item("Dry Coconut", "सूखा नारियल", "Groceries", "South Indian Staples", "non_perishable", "south", "kg", "Dry store"),
    item("Penne Pasta", "पेने पास्ता", "Groceries", "Pasta & Noodles", "non_perishable", "continental", "kg", "Dry store"),
    item("Spaghetti", "स्पेगेटी", "Groceries", "Pasta & Noodles", "non_perishable", "continental", "kg", "Dry store"),
    item("Hakka Noodles", "हक्का नूडल्स", "Groceries", "Pasta & Noodles", "non_perishable", "chinese", "kg", "Dry store"),

    # Oils, sauces, spreads, and condiments
    item("Refined Oil", "रिफाइंड तेल", "Sauces & Condiments", "Cooking Oils", "non_perishable", "kitchen", "litre", "Oil store"),
    item("Mustard Oil", "सरसों का तेल", "Sauces & Condiments", "Cooking Oils", "non_perishable", "north", "litre", "Oil store"),
    item("Olive Oil", "जैतून का तेल", "Sauces & Condiments", "Cooking Oils", "non_perishable", "continental", "litre", "Oil store"),
    item("Sesame Oil", "तिल का तेल", "Sauces & Condiments", "Cooking Oils", "non_perishable", "chinese", "litre", "Oil store"),
    item("Tandoori Spread Sauce", "तंदूरी स्प्रेड सॉस", "Sauces & Condiments", "Spreads", "non_perishable", "continental", "bottle", "Refrigerator after opening"),
    item("Sandwich Spread", "सैंडविच स्प्रेड", "Sauces & Condiments", "Spreads", "non_perishable", "continental", "bottle", "Refrigerator after opening"),
    item("Mayonnaise", "मेयोनीज़", "Sauces & Condiments", "Spreads", "non_perishable", "continental", "kg", "Refrigerator after opening"),
    item("Pizza Sauce", "पिज़्ज़ा सॉस", "Sauces & Condiments", "Continental Sauces", "non_perishable", "continental", "kg", "Refrigerator after opening"),
    item("Tomato Puree", "टमाटर प्यूरी", "Sauces & Condiments", "Continental Sauces", "non_perishable", "continental", "tin", "Dry store"),
    item("Pesto Sauce", "पेस्टो सॉस", "Sauces & Condiments", "Continental Sauces", "perishable", "continental", "bottle", "Refrigerator"),
    item("Green Chilli Sauce", "हरी मिर्च सॉस", "Sauces & Condiments", "Indo-Chinese Sauces", "non_perishable", "chinese", "bottle", "Sauce shelf"),
    item("Red Chilli Sauce", "लाल मिर्च सॉस", "Sauces & Condiments", "Indo-Chinese Sauces", "non_perishable", "chinese", "bottle", "Sauce shelf"),
    item("Tomato Ketchup", "टमाटर केचप", "Sauces & Condiments", "Table Sauces", "non_perishable", "cafe", "kg", "Sauce shelf"),
    item("Soy Sauce", "सोया सॉस", "Sauces & Condiments", "Indo-Chinese Sauces", "non_perishable", "chinese", "bottle", "Sauce shelf"),
    item("Schezwan Sauce", "शेजवान सॉस", "Sauces & Condiments", "Indo-Chinese Sauces", "non_perishable", "chinese", "kg", "Refrigerator after opening"),
    item("White Vinegar", "सफेद सिरका", "Sauces & Condiments", "Indo-Chinese Sauces", "non_perishable", "chinese", "bottle", "Sauce shelf"),
    item("Chilli Oil", "चिली ऑयल", "Sauces & Condiments", "Indo-Chinese Sauces", "non_perishable", "chinese", "bottle", "Sauce shelf"),
    item("Jalapeno Slices", "जलापेनो स्लाइस", "Sauces & Condiments", "Continental Condiments", "non_perishable", "continental", "jar", "Refrigerator after opening"),
    item("Black Olives", "काले जैतून", "Sauces & Condiments", "Continental Condiments", "non_perishable", "continental", "jar", "Refrigerator after opening"),

    # Masalas, spices, seasonings, and baking agents
    item("Salt", "नमक", "Masalas & Seasonings", "Basic Seasonings", "non_perishable", "kitchen", "kg", "Dry store"),
    item("Black Salt", "काला नमक", "Masalas & Seasonings", "Basic Seasonings", "non_perishable", "barista", "kg", "Dry store"),
    item("Black Pepper", "काली मिर्च", "Masalas & Seasonings", "Whole & Ground Spices", "non_perishable", "kitchen", "kg", "Dry store"),
    item("Asafoetida", "हींग", "Masalas & Seasonings", "Whole & Ground Spices", "non_perishable", "south", "packet", "Dry store"),
    item("Turmeric Powder", "हल्दी पाउडर", "Masalas & Seasonings", "Ground Masalas", "non_perishable", "kitchen", "kg", "Dry store"),
    item("Red Chilli Powder", "लाल मिर्च पाउडर", "Masalas & Seasonings", "Ground Masalas", "non_perishable", "kitchen", "kg", "Dry store"),
    item("Coriander Powder", "धनिया पाउडर", "Masalas & Seasonings", "Ground Masalas", "non_perishable", "north", "kg", "Dry store"),
    item("Cumin Seeds", "जीरा", "Masalas & Seasonings", "Whole & Ground Spices", "non_perishable", "kitchen", "kg", "Dry store"),
    item("Mustard Seeds", "राई", "Masalas & Seasonings", "Whole & Ground Spices", "non_perishable", "south", "kg", "Dry store"),
    item("Fenugreek Seeds", "मेथी दाना", "Masalas & Seasonings", "Whole & Ground Spices", "non_perishable", "south", "kg", "Dry store"),
    item("Fennel Seeds", "सौंफ", "Masalas & Seasonings", "Whole & Ground Spices", "non_perishable", "north", "kg", "Dry store"),
    item("Carom Seeds", "अजवाइन", "Masalas & Seasonings", "Whole & Ground Spices", "non_perishable", "north", "kg", "Dry store"),
    item("Garam Masala", "गरम मसाला", "Masalas & Seasonings", "Ground Masalas", "non_perishable", "north", "kg", "Dry store"),
    item("Chaat Masala", "चाट मसाला", "Masalas & Seasonings", "Ground Masalas", "non_perishable", "north", "kg", "Dry store"),
    item("Pav Bhaji Masala", "पाव भाजी मसाला", "Masalas & Seasonings", "Ground Masalas", "non_perishable", "north", "kg", "Dry store"),
    item("Sambar Masala", "सांभर मसाला", "Masalas & Seasonings", "South Indian Masalas", "non_perishable", "south", "kg", "Dry store"),
    item("Rasam Powder", "रसम पाउडर", "Masalas & Seasonings", "South Indian Masalas", "non_perishable", "south", "kg", "Dry store"),
    item("Tandoori Masala", "तंदूरी मसाला", "Masalas & Seasonings", "Ground Masalas", "non_perishable", "north", "kg", "Dry store"),
    item("Kitchen King Masala", "किचन किंग मसाला", "Masalas & Seasonings", "Ground Masalas", "non_perishable", "north", "kg", "Dry store"),
    item("Kasuri Methi", "कसूरी मेथी", "Masalas & Seasonings", "Dried Herbs", "non_perishable", "north", "kg", "Dry store"),
    item("Oregano", "ओरिगैनो", "Masalas & Seasonings", "Continental Seasonings", "non_perishable", "continental", "packet", "Dry store"),
    item("Chilli Flakes", "चिली फ्लेक्स", "Masalas & Seasonings", "Continental Seasonings", "non_perishable", "continental", "packet", "Dry store"),
    item("Cinnamon", "दालचीनी", "Masalas & Seasonings", "Whole & Ground Spices", "non_perishable", "barista", "kg", "Dry store"),
    item("Green Cardamom", "हरी इलायची", "Masalas & Seasonings", "Whole & Ground Spices", "non_perishable", "barista", "kg", "Dry store"),
    item("Cloves", "लौंग", "Masalas & Seasonings", "Whole & Ground Spices", "non_perishable", "barista", "kg", "Dry store"),
    item("Bay Leaves", "तेज पत्ता", "Masalas & Seasonings", "Whole & Ground Spices", "non_perishable", "north", "kg", "Dry store"),
    item("Baking Soda", "बेकिंग सोडा", "Masalas & Seasonings", "Baking Agents", "non_perishable", "continental", "packet", "Dry store"),
    item("Baking Powder", "बेकिंग पाउडर", "Masalas & Seasonings", "Baking Agents", "non_perishable", "continental", "packet", "Dry store"),
    item("Dry Yeast", "सूखा खमीर", "Masalas & Seasonings", "Baking Agents", "non_perishable", "continental", "packet", "Refrigerator after opening"),

    # Packaging, disposables, and customer service consumables
    item("Parcel Box 350 mL", "पार्सल डिब्बा 350 मिली", "Packaging & Disposables", "Food Containers", "non_perishable", "cafe", "pcs", "Packaging store"),
    item("Parcel Box 500 mL", "पार्सल डिब्बा 500 मिली", "Packaging & Disposables", "Food Containers", "non_perishable", "cafe", "pcs", "Packaging store"),
    item("Parcel Box 650 mL", "पार्सल डिब्बा 650 मिली", "Packaging & Disposables", "Food Containers", "non_perishable", "cafe", "pcs", "Packaging store"),
    item("Transparent Sipper Glass 250 mL", "पारदर्शी सिपर गिलास 250 मिली", "Packaging & Disposables", "Cold Drink Cups", "non_perishable", "barista", "pcs", "Packaging store"),
    item("Transparent Sipper Glass 320 mL", "पारदर्शी सिपर गिलास 320 मिली", "Packaging & Disposables", "Cold Drink Cups", "non_perishable", "barista", "pcs", "Packaging store"),
    item("Paper Cup 100 mL", "पेपर कप 100 मिली", "Packaging & Disposables", "Hot Drink Cups", "non_perishable", "barista", "pcs", "Packaging store"),
    item("Paper Cup 200 mL", "पेपर कप 200 मिली", "Packaging & Disposables", "Hot Drink Cups", "non_perishable", "barista", "pcs", "Packaging store"),
    item("Paper Cup 300 mL", "पेपर कप 300 मिली", "Packaging & Disposables", "Hot Drink Cups", "non_perishable", "barista", "pcs", "Packaging store"),
    item("Cup Lids", "कप ढक्कन", "Packaging & Disposables", "Cup Accessories", "non_perishable", "barista", "pcs", "Packaging store"),
    item("Paper Straws", "पेपर स्ट्रॉ", "Packaging & Disposables", "Cup Accessories", "non_perishable", "barista", "packet", "Packaging store"),
    item("Wooden Stirrers", "लकड़ी स्टिरर", "Packaging & Disposables", "Cup Accessories", "non_perishable", "barista", "packet", "Packaging store"),
    item("Paper Carry Bags", "कागज का कैरी बैग", "Packaging & Disposables", "Takeaway Bags", "non_perishable", "cafe", "pcs", "Packaging store"),
    item("Aluminium Foil", "एल्युमिनियम फॉयल", "Packaging & Disposables", "Wrapping", "non_perishable", "kitchen", "roll", "Packaging store"),
    item("Cling Film", "क्लिंग फिल्म", "Packaging & Disposables", "Wrapping", "non_perishable", "kitchen", "roll", "Packaging store"),
    item("Butter Paper", "बटर पेपर", "Packaging & Disposables", "Wrapping", "non_perishable", "continental", "packet", "Packaging store"),
    item("Disposable Gloves", "डिस्पोजेबल दस्ताने", "Packaging & Disposables", "Food Safety", "non_perishable", "kitchen", "box", "Hygiene store"),
    item("Hair Nets", "हेयर नेट", "Packaging & Disposables", "Food Safety", "non_perishable", "kitchen", "packet", "Hygiene store"),
    item("Paper Napkins", "पेपर नैपकिन", "Packaging & Disposables", "Table Service", "non_perishable", "cafe", "packet", "Service store"),
    item("Disposable Plates", "डिस्पोजेबल प्लेट", "Packaging & Disposables", "Table Service", "non_perishable", "cafe", "pcs", "Service store"),
    item("Disposable Bowls", "डिस्पोजेबल कटोरी", "Packaging & Disposables", "Table Service", "non_perishable", "cafe", "pcs", "Service store"),
    item("Disposable Spoons", "डिस्पोजेबल चम्मच", "Packaging & Disposables", "Table Service", "non_perishable", "cafe", "pcs", "Service store"),
    item("Disposable Forks", "डिस्पोजेबल कांटा", "Packaging & Disposables", "Table Service", "non_perishable", "cafe", "pcs", "Service store"),
    item("Toothpicks", "टूथपिक", "Packaging & Disposables", "Table Service", "non_perishable", "cafe", "box", "Service store"),

    # Cleaning, hygiene, and washroom supplies
    item("Dishwashing Liquid", "बर्तन धोने का तरल", "Cleaning Products", "Dishwashing", "non_perishable", "kitchen", "litre", "Cleaning store"),
    item("Dishwasher Detergent", "डिशवॉशर डिटर्जेंट", "Cleaning Products", "Dishwashing", "non_perishable", "kitchen", "kg", "Cleaning store"),
    item("Floor Cleaner", "फर्श क्लीनर", "Cleaning Products", "Floor Care", "non_perishable", "cafe", "litre", "Cleaning store"),
    item("Toilet Cleaner", "टॉयलेट क्लीनर", "Cleaning Products", "Washroom Cleaning", "non_perishable", "cafe", "litre", "Cleaning store"),
    item("Glass Cleaner", "कांच क्लीनर", "Cleaning Products", "Surface Care", "non_perishable", "cafe", "litre", "Cleaning store"),
    item("Kitchen Degreaser", "किचन डीग्रीज़र", "Cleaning Products", "Kitchen Cleaning", "non_perishable", "kitchen", "litre", "Cleaning store"),
    item("Food-Safe Surface Sanitizer", "फूड सेफ सैनिटाइज़र", "Cleaning Products", "Kitchen Cleaning", "non_perishable", "kitchen", "litre", "Cleaning store"),
    item("Bleach", "ब्लीच", "Cleaning Products", "Disinfectants", "non_perishable", "cafe", "litre", "Cleaning store"),
    item("Phenyl", "फिनाइल", "Cleaning Products", "Floor Care", "non_perishable", "cafe", "litre", "Cleaning store"),
    item("Laundry Detergent", "कपड़े धोने का डिटर्जेंट", "Cleaning Products", "Laundry", "non_perishable", "cafe", "kg", "Cleaning store"),
    item("Scrub Pads", "स्क्रब पैड", "Cleaning Products", "Cleaning Tools", "non_perishable", "kitchen", "packet", "Cleaning store"),
    item("Steel Wool", "स्टील स्क्रबर", "Cleaning Products", "Cleaning Tools", "non_perishable", "kitchen", "packet", "Cleaning store"),
    item("Microfiber Cloth", "माइक्रोफाइबर कपड़ा", "Cleaning Products", "Cleaning Tools", "non_perishable", "cafe", "pcs", "Cleaning store"),
    item("Floor Mop", "फर्श पोछा", "Cleaning Products", "Cleaning Tools", "non_perishable", "cafe", "pcs", "Cleaning store"),
    item("Broom", "झाड़ू", "Cleaning Products", "Cleaning Tools", "non_perishable", "cafe", "pcs", "Cleaning store"),
    item("Dustpan", "डस्टपैन", "Cleaning Products", "Cleaning Tools", "non_perishable", "cafe", "pcs", "Cleaning store"),
    item("Cleaning Gloves", "सफाई के दस्ताने", "Cleaning Products", "Protective Supplies", "non_perishable", "cafe", "pair", "Cleaning store"),
    item("Drain Cleaner", "नाली क्लीनर", "Cleaning Products", "Washroom Cleaning", "non_perishable", "cafe", "litre", "Cleaning store"),
    item("Garbage Bags Small", "छोटे कचरा बैग", "Cleaning Products", "Waste Disposal", "non_perishable", "cafe", "roll", "Cleaning store"),
    item("Garbage Bags Large", "बड़े कचरा बैग", "Cleaning Products", "Waste Disposal", "non_perishable", "cafe", "roll", "Cleaning store"),
    item("Insect Spray", "कीट स्प्रे", "Cleaning Products", "Pest Control", "non_perishable", "cafe", "bottle", "Locked chemical store"),
    item("Cockroach Gel", "कॉकरोच जेल", "Cleaning Products", "Pest Control", "non_perishable", "cafe", "tube", "Locked chemical store"),
    item("Hand Wash", "हैंड वॉश", "Toiletries & Washroom", "Hand Hygiene", "non_perishable", "cafe", "litre", "Washroom store"),
    item("Hand Sanitizer", "हैंड सैनिटाइज़र", "Toiletries & Washroom", "Hand Hygiene", "non_perishable", "cafe", "litre", "Washroom store"),
    item("Toilet Paper Roll", "टॉयलेट पेपर रोल", "Toiletries & Washroom", "Paper Products", "non_perishable", "cafe", "roll", "Washroom store"),
    item("Paper Hand Towels", "पेपर हैंड टॉवल", "Toiletries & Washroom", "Paper Products", "non_perishable", "cafe", "packet", "Washroom store"),
    item("Facial Tissues", "फेशियल टिश्यू", "Toiletries & Washroom", "Paper Products", "non_perishable", "cafe", "box", "Washroom store"),
    item("Urinal Cubes", "यूरिनल क्यूब", "Toiletries & Washroom", "Odour Control", "non_perishable", "cafe", "packet", "Washroom store"),
    item("Air Freshener", "एयर फ्रेशनर", "Toiletries & Washroom", "Odour Control", "non_perishable", "cafe", "bottle", "Washroom store"),
    item("Sanitary Disposal Bags", "सैनिटरी डिस्पोजल बैग", "Toiletries & Washroom", "Waste Disposal", "non_perishable", "cafe", "packet", "Washroom store"),

    # Utensils, serving ware, machinery, and maintenance stock
    item("Stainless Steel Plates", "स्टील प्लेट", "Kitchen Supplies", "Crockery & Serveware", "non_perishable", "cafe", "pcs", "Service store"),
    item("Stainless Steel Bowls", "स्टील कटोरी", "Kitchen Supplies", "Crockery & Serveware", "non_perishable", "cafe", "pcs", "Service store"),
    item("Ceramic Cups", "सिरेमिक कप", "Kitchen Supplies", "Crockery & Serveware", "non_perishable", "barista", "pcs", "Service store"),
    item("Glass Tumblers", "कांच गिलास", "Kitchen Supplies", "Crockery & Serveware", "non_perishable", "cafe", "pcs", "Service store"),
    item("Table Spoons", "टेबल चम्मच", "Kitchen Supplies", "Cutlery", "non_perishable", "cafe", "pcs", "Service store"),
    item("Table Forks", "टेबल कांटा", "Kitchen Supplies", "Cutlery", "non_perishable", "cafe", "pcs", "Service store"),
    item("Table Knives", "टेबल चाकू", "Kitchen Supplies", "Cutlery", "non_perishable", "cafe", "pcs", "Service store"),
    item("Chef Knife", "शेफ चाकू", "Kitchen Supplies", "Knives", "non_perishable", "kitchen", "pcs", "Knife rack"),
    item("Paring Knife", "छोटा चाकू", "Kitchen Supplies", "Knives", "non_perishable", "kitchen", "pcs", "Knife rack"),
    item("Chopping Board", "चॉपिंग बोर्ड", "Kitchen Supplies", "Preparation Tools", "non_perishable", "kitchen", "pcs", "Utensil rack"),
    item("Stainless Steel Kadai", "स्टील कड़ाही", "Kitchen Supplies", "Cookware", "non_perishable", "kitchen", "pcs", "Utensil rack"),
    item("Frying Pan", "फ्राइंग पैन", "Kitchen Supplies", "Cookware", "non_perishable", "continental", "pcs", "Utensil rack"),
    item("Dosa Tawa", "डोसा तवा", "Kitchen Supplies", "Cookware", "non_perishable", "south", "pcs", "South kitchen"),
    item("Pressure Cooker", "प्रेशर कुकर", "Kitchen Supplies", "Cookware", "non_perishable", "kitchen", "pcs", "Utensil rack"),
    item("Saucepan", "सॉस पैन", "Kitchen Supplies", "Cookware", "non_perishable", "barista", "pcs", "Utensil rack"),
    item("Ladle", "करछी", "Kitchen Supplies", "Preparation Tools", "non_perishable", "kitchen", "pcs", "Utensil rack"),
    item("Spatula", "पलटा", "Kitchen Supplies", "Preparation Tools", "non_perishable", "kitchen", "pcs", "Utensil rack"),
    item("Fine Strainer", "बारीक छलनी", "Kitchen Supplies", "Preparation Tools", "non_perishable", "barista", "pcs", "Utensil rack"),
    item("Measuring Cups", "मापने के कप", "Kitchen Supplies", "Measurement", "non_perishable", "kitchen", "set", "Utensil rack"),
    item("Digital Kitchen Scale", "डिजिटल किचन तराजू", "Kitchen Supplies", "Measurement", "non_perishable", "kitchen", "pcs", "Kitchen counter"),
    item("Food Storage Container", "खाद्य भंडारण डिब्बा", "Kitchen Supplies", "Storage", "non_perishable", "kitchen", "pcs", "Storage rack"),
    item("Gas Cylinder", "गैस सिलेंडर", "Gas & Fuel", "Cooking Fuel", "non_perishable", "kitchen", "pcs", "Ventilated gas bank"),
    item("Commercial Gas Range", "कमर्शियल गैस रेंज", "Maintenance & Equipment", "Cooking Equipment", "non_perishable", "kitchen", "pcs", "Kitchen line"),
    item("Induction Cooktop", "इंडक्शन चूल्हा", "Maintenance & Equipment", "Cooking Equipment", "non_perishable", "kitchen", "pcs", "Kitchen line"),
    item("Mixer Grinder", "मिक्सर ग्राइंडर", "Maintenance & Equipment", "Preparation Equipment", "non_perishable", "kitchen", "pcs", "Equipment counter"),
    item("Commercial Blender", "कमर्शियल ब्लेंडर", "Maintenance & Equipment", "Beverage Equipment", "non_perishable", "barista", "pcs", "Barista counter"),
    item("Juice Extractor", "जूस मशीन", "Maintenance & Equipment", "Beverage Equipment", "non_perishable", "barista", "pcs", "Barista counter"),
    item("Espresso Machine", "एस्प्रेसो मशीन", "Maintenance & Equipment", "Coffee Equipment", "non_perishable", "barista", "pcs", "Barista counter"),
    item("Coffee Grinder", "कॉफी ग्राइंडर", "Maintenance & Equipment", "Coffee Equipment", "non_perishable", "barista", "pcs", "Barista counter"),
    item("Water Purifier Filter", "वाटर प्यूरिफायर फिल्टर", "Maintenance & Equipment", "Filters & Spares", "non_perishable", "cafe", "pcs", "Maintenance store"),
    item("Refrigerator Thermometer", "फ्रिज थर्मामीटर", "Maintenance & Equipment", "Safety & Monitoring", "non_perishable", "kitchen", "pcs", "Refrigerator"),
    item("Fire Extinguisher", "अग्निशामक यंत्र", "Maintenance & Equipment", "Safety Equipment", "non_perishable", "cafe", "pcs", "Marked safety point"),
    item("First Aid Kit", "प्राथमिक उपचार किट", "Maintenance & Equipment", "Safety Equipment", "non_perishable", "cafe", "kit", "Office"),
    item("LED Bulb", "एलईडी बल्ब", "Utility", "Electrical Supplies", "non_perishable", "cafe", "pcs", "Maintenance store"),
    item("Extension Board", "एक्सटेंशन बोर्ड", "Utility", "Electrical Supplies", "non_perishable", "cafe", "pcs", "Maintenance store"),
    item("Receipt Paper Roll", "रसीद पेपर रोल", "Utility", "POS Supplies", "non_perishable", "cafe", "roll", "Cash counter"),
    item("Printer Ink", "प्रिंटर इंक", "Utility", "Office Supplies", "non_perishable", "cafe", "cartridge", "Office"),
    item("Permanent Marker", "परमानेंट मार्कर", "Utility", "Labelling Supplies", "non_perishable", "cafe", "pcs", "Office"),
    item("Inventory Labels", "इन्वेंटरी लेबल", "Utility", "Labelling Supplies", "non_perishable", "cafe", "roll", "Office"),
]


# Old spellings, brands, and shorthand are resolved to one canonical record.
ITEM_ALIASES = {
    "amul fresh cream": "Fresh Cream",
    "amul gold fresh milk": "Fresh Milk",
    "amul gold milk box": "UHT Milk Carton",
    "burger bun": "Burger Buns",
    "capsicum": "Green Capsicum",
    "coriander": "Fresh Coriander Leaves",
    "green chilli": "Fresh Green Chilli",
    "fresh chilli": "Fresh Green Chilli",
    "mint": "Mint Leaves",
    "dahi": "Curd",
    "desh ghee": "Desi Ghee",
    "mozzerrela cheese": "Mozzarella Cheese",
    "soya sauce": "Soy Sauce",
    "chat masala": "Chaat Masala",
    "jeera": "Cumin Seeds",
    "hing": "Asafoetida",
    "bottlegaurd": "Bottle Gourd",
    "bottle gaurd": "Bottle Gourd",
    "cauliflaower": "Cauliflower",
    "lettuse": "Lettuce",
    "beatroot": "Beetroot",
}
